#ifndef _ERROR_H
#define _ERROR_H

#define CARD_INVALID_VAL    -1

#define ALREADY_WRITING -100
#define SEND_BUF_TIMEOUT -101
#define BCAST_BUF_TIMEOUT -102

#define READ_INCOMPLETE -200
#define INVALID_PACKAGE -201
#endif
